#pragma once

#define ID_PLUGINGUI_FIRST_COMMAND   					0x8000
#define ID_EDITMODE                     				(ID_PLUGINGUI_FIRST_COMMAND)
#define ID_INSERT_KNOB                  				(ID_PLUGINGUI_FIRST_COMMAND + 1)
#define ID_INSERT_SLIDER                				(ID_PLUGINGUI_FIRST_COMMAND + 2)
#define ID_INSERT_PAD                   				(ID_PLUGINGUI_FIRST_COMMAND + 3)
#define ID_INSERT_BUTTON                				(ID_PLUGINGUI_FIRST_COMMAND + 4)
#define ID_INSERT_ENVELOP                				(ID_PLUGINGUI_FIRST_COMMAND + 5)
#define ID_PLUGINGUI_EDIT_SHOWGRID						(ID_PLUGINGUI_FIRST_COMMAND + 6)

// Layout commands
#define ID_PLUGINGUI_FIRST_LAYOUT_COMMAND   					0x8100
#define ID_PLUGINGUI_ALIGHN_TO_GRID						(ID_PLUGINGUI_FIRST_LAYOUT_COMMAND )
#define ID_PLUGINGUI_ALIGHN_LEFTS						(ID_PLUGINGUI_FIRST_LAYOUT_COMMAND + 1)
#define ID_PLUGINGUI_ALIGHN_CENTERS						(ID_PLUGINGUI_FIRST_LAYOUT_COMMAND + 2)
#define ID_PLUGINGUI_ALIGHN_RIGHTS						(ID_PLUGINGUI_FIRST_LAYOUT_COMMAND + 3)
#define ID_PLUGINGUI_ALIGHN_TOPS						(ID_PLUGINGUI_FIRST_LAYOUT_COMMAND + 4)
#define ID_PLUGINGUI_ALIGHN_MIDDLES						(ID_PLUGINGUI_FIRST_LAYOUT_COMMAND + 5)
#define ID_PLUGINGUI_ALIGHN_BOTTOMS						(ID_PLUGINGUI_FIRST_LAYOUT_COMMAND + 6)
#define ID_PLUGINGUI_MAKE_SAME_WIDTH					(ID_PLUGINGUI_FIRST_LAYOUT_COMMAND + 7)
#define ID_PLUGINGUI_MAKE_SAME_HEIGHT					(ID_PLUGINGUI_FIRST_LAYOUT_COMMAND + 8)
#define ID_PLUGINGUI_MAKE_SAME_SIZE						(ID_PLUGINGUI_FIRST_LAYOUT_COMMAND + 9)
#define ID_PLUGINGUI_SIZE_TO_GRID						(ID_PLUGINGUI_FIRST_LAYOUT_COMMAND + 10)
#define ID_PLUGINGUI_MAKE_HORIZONTAL_SPACING_EQUAL		(ID_PLUGINGUI_FIRST_LAYOUT_COMMAND + 11)
#define ID_PLUGINGUI_MAKE_VERTIAL_SPACING_EQUAL			(ID_PLUGINGUI_FIRST_LAYOUT_COMMAND + 12)
#define ID_PLUGINGUI_BRING_TO_FRONT						(ID_PLUGINGUI_FIRST_LAYOUT_COMMAND + 13)
#define ID_PLUGINGUI_SEND_TO_BACK						(ID_PLUGINGUI_FIRST_LAYOUT_COMMAND + 14)

#define ID_PLUGINGUI_FIRST_CONTROL_COMMAND   					0x8200

#define ID_PLUGINGUI_ENVELOP_FLIP_HORIZONTAL			(ID_PLUGINGUI_FIRST_CONTROL_COMMAND)
#define ID_PLUGINGUI_ENVELOP_FLIP_VERTICAL				(ID_PLUGINGUI_FIRST_CONTROL_COMMAND + 1)
#define ID_PLUGINGUI_ENVELOP_FLIP_BY_CENTER				(ID_PLUGINGUI_FIRST_CONTROL_COMMAND + 2)
#define ID_PLUGINGUI_ENVELOP_REMOVE_SELECTED_POINTS		(ID_PLUGINGUI_FIRST_CONTROL_COMMAND + 3)
#define ID_PLUGINGUI_ENVELOP_CHANGE_CURVE_POWER			(ID_PLUGINGUI_FIRST_CONTROL_COMMAND + 4)
#define ID_PLUGINGUI_ENVELOP_CHANGE_CURVE_BEZIER		(ID_PLUGINGUI_FIRST_CONTROL_COMMAND + 5)

#define ID_PLUGINGUI_LAST_CONTROL_COMMAND   					0x9000
